site_name: Ares-LoRa
repo_url: https://github.com/deep-spectrum/ares-lora/
repo_name: deep-spectrum/ares-lora
nav:
  - Home: index.md
  - Communication:
      - Home: communications/index.md
      - Frames: communications/ares-frame.md
      - Packets: communications/ares-packet.md
  - Serial Driver:
      - Home: serial-driver/index.md
      - Python API:
          - Serial Driver: serial-driver/python-api/serial_driver.md
          - Device Firmware Update: serial-driver/python-api/dfu.md
          - Utilities: serial-driver/python-api/utils.md
      - C++ API:
          - Code Standards: serial-driver/standards.md
          - Code Documentation: 'serial-driver/cpp-api/html/index.html" target="_blank'
  - Firmware:
      - Home: firmware/index.md
      - Code Standards: firmware/standards.md
      - Code Documentation: 'firmware/firmware-docs/html/index.html" target="_blank'

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  icon:
    logo: material/antenna
    annotation: material/arrow-right-circle
  font:
    code: monospace
  features:
    - navigation.instant
    - navigation.expand
    - navigation.tabs
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep orange
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      accent: red
      toggle:
        icon: material/weather-night
        name: Switch to system preference


plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python_xref
      handlers:
        python_xref:
          options:
            docstring_style: google
            relative_crossrefs: true
            separate_signature: true
            line_length: 80
            show_signature_annotations: true
            signature_crossrefs: true
            show_root_full_path: true
            show_root_members_full_path: true
            show_symbol_type_heading: true
            show_root_heading: true
            show_root_toc_entry: true
            heading_level: 1
            check_crossrefs_exclude:
              - "^jax\\.(.*)"
              - "^numpy\\.(.*)"
          inventories:
            - https://docs.python.org/3/objects.inv
            - https://numpy.org/doc/stable/objects.inv
            - https://docs.jax.dev/en/latest/objects.inv

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - footnotes
