CONFIG_LOG=y
CONFIG_MCUBOOT_LOG_LEVEL_WRN=y

CONFIG_MCUBOOT_SERIAL=y
CONFIG_UART_CONSOLE=n
CONFIG_SINGLE_APPLICATION_SLOT=n
CONFIG_MCUBOOT_INDICATION_LED=y
CONFIG_BOOT_SERIAL_CDC_ACM=y

CONFIG_PM_PARTITION_SIZE_MCUBOOT=0x11000
CONFIG_BOOT_MAX_IMG_SECTORS=512

CONFIG_BOOT_SERIAL_ENTRANCE_GPIO=n
CONFIG_BOOT_SERIAL_NO_APPLICATION=y
