CONFIG_LOG=n

CONFIG_MCUBOOT_SERIAL=y
CONFIG_UART_CONSOLE=n
CONFIG_SINGLE_APPLICATION_SLOT=y
CONFIG_MCUBOOT_INDICATION_LED=n
CONFIG_BOOT_SERIAL_CDC_ACM=y

CONFIG_PM_PARTITION_SIZE_MCUBOOT=0x11000
CONFIG_BOOT_MAX_IMG_SECTORS=512

CONFIG_BOOT_SERIAL_ENTRANCE_GPIO=n
CONFIG_BOOT_SERIAL_WAIT_FOR_DFU=y
CONFIG_BOOT_SERIAL_BOOT_MODE=n
CONFIG_BOOT_SERIAL_PIN_RESET=n
