CONFIG_USB_DEVICE_STACK_NEXT=y
# CONFIG_CDC_ACM_SERIAL_INITIALIZE_AT_BOOT=y
# CONFIG_CDC_ACM_SERIAL_PID=0x0004
# CONFIG_CDC_ACM_SERIAL_PRODUCT_STRING="LoRa Start"
# CONFIG_CDC_ACM_SERIAL_MANUFACTURER_STRING="CMU"
CONFIG_UART_USE_RUNTIME_CONFIGURE=y
CONFIG_USBD_CDC_ACM_CLASS=y
